// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	GameUserData
	Hello
	UserLoginRequest
	UserLoginResponse
	UserLogoutRequest
	UserLogoutResponse
	UserRegisterRequest
	UserRegisterResponse
	UserEnterRoomRequest
	UserEnterRoomResponse
	UserOutOfRoomRequest
	UserOutOfRoomResponse
	OthersEnterTable
	OthersLeaveTable
	UserFinishesLoadingRequest
	UserMessageErrorResponse
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageId int32

const (
	MessageId__Hello            MessageId = 0
	MessageId__UserLoginRequest MessageId = 1
)

var MessageId_name = map[int32]string{
	0: "_Hello",
	1: "_UserLoginRequest",
}
var MessageId_value = map[string]int32{
	"_Hello":            0,
	"_UserLoginRequest": 1,
}

func (x MessageId) String() string {
	return proto.EnumName(MessageId_name, int32(x))
}
func (MessageId) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GameUserData struct {
}

func (m *GameUserData) Reset()                    { *m = GameUserData{} }
func (m *GameUserData) String() string            { return proto.CompactTextString(m) }
func (*GameUserData) ProtoMessage()               {}
func (*GameUserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 0
type Hello struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Hello) Reset()                    { *m = Hello{} }
func (m *Hello) String() string            { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()               {}
func (*Hello) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Hello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 1登录请求
type UserLoginRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *UserLoginRequest) Reset()                    { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()               {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserLoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 2登录回复
type UserLoginResponse struct {
	Resultcode    int32  `protobuf:"varint,1,opt,name=Resultcode,json=resultcode" json:"Resultcode,omitempty"`
	NotifyMessage string `protobuf:"bytes,2,opt,name=NotifyMessage,json=notifyMessage" json:"NotifyMessage,omitempty"`
}

func (m *UserLoginResponse) Reset()                    { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()               {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserLoginResponse) GetResultcode() int32 {
	if m != nil {
		return m.Resultcode
	}
	return 0
}

func (m *UserLoginResponse) GetNotifyMessage() string {
	if m != nil {
		return m.NotifyMessage
	}
	return ""
}

// 3注销请求
type UserLogoutRequest struct {
}

func (m *UserLogoutRequest) Reset()                    { *m = UserLogoutRequest{} }
func (m *UserLogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*UserLogoutRequest) ProtoMessage()               {}
func (*UserLogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 4注销回复
type UserLogoutResponse struct {
	Resultcode    int32  `protobuf:"varint,1,opt,name=Resultcode,json=resultcode" json:"Resultcode,omitempty"`
	NotifyMessage string `protobuf:"bytes,2,opt,name=NotifyMessage,json=notifyMessage" json:"NotifyMessage,omitempty"`
}

func (m *UserLogoutResponse) Reset()                    { *m = UserLogoutResponse{} }
func (m *UserLogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*UserLogoutResponse) ProtoMessage()               {}
func (*UserLogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserLogoutResponse) GetResultcode() int32 {
	if m != nil {
		return m.Resultcode
	}
	return 0
}

func (m *UserLogoutResponse) GetNotifyMessage() string {
	if m != nil {
		return m.NotifyMessage
	}
	return ""
}

// 5
type UserRegisterRequest struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password" json:"Password,omitempty"`
}

func (m *UserRegisterRequest) Reset()                    { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()               {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UserRegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserRegisterResponse struct {
	Resultcode    int32  `protobuf:"varint,1,opt,name=Resultcode,json=resultcode" json:"Resultcode,omitempty"`
	NotifyMessage string `protobuf:"bytes,2,opt,name=NotifyMessage,json=notifyMessage" json:"NotifyMessage,omitempty"`
}

func (m *UserRegisterResponse) Reset()                    { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()               {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserRegisterResponse) GetResultcode() int32 {
	if m != nil {
		return m.Resultcode
	}
	return 0
}

func (m *UserRegisterResponse) GetNotifyMessage() string {
	if m != nil {
		return m.NotifyMessage
	}
	return ""
}

// 100进入房间请求
type UserEnterRoomRequest struct {
	RoomId int32 `protobuf:"varint,1,opt,name=RoomId,json=roomId" json:"RoomId,omitempty"`
}

func (m *UserEnterRoomRequest) Reset()                    { *m = UserEnterRoomRequest{} }
func (m *UserEnterRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*UserEnterRoomRequest) ProtoMessage()               {}
func (*UserEnterRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserEnterRoomRequest) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// 101进入房间回复
type UserEnterRoomResponse struct {
	Resultcode    int32  `protobuf:"varint,1,opt,name=Resultcode,json=resultcode" json:"Resultcode,omitempty"`
	NotifyMessage string `protobuf:"bytes,2,opt,name=NotifyMessage,json=notifyMessage" json:"NotifyMessage,omitempty"`
	TableId       int32  `protobuf:"varint,3,opt,name=TableId,json=tableId" json:"TableId,omitempty"`
	ChairId       int32  `protobuf:"varint,4,opt,name=ChairId,json=chairId" json:"ChairId,omitempty"`
}

func (m *UserEnterRoomResponse) Reset()                    { *m = UserEnterRoomResponse{} }
func (m *UserEnterRoomResponse) String() string            { return proto.CompactTextString(m) }
func (*UserEnterRoomResponse) ProtoMessage()               {}
func (*UserEnterRoomResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserEnterRoomResponse) GetResultcode() int32 {
	if m != nil {
		return m.Resultcode
	}
	return 0
}

func (m *UserEnterRoomResponse) GetNotifyMessage() string {
	if m != nil {
		return m.NotifyMessage
	}
	return ""
}

func (m *UserEnterRoomResponse) GetTableId() int32 {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *UserEnterRoomResponse) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

// 102退出房间请求
type UserOutOfRoomRequest struct {
}

func (m *UserOutOfRoomRequest) Reset()                    { *m = UserOutOfRoomRequest{} }
func (m *UserOutOfRoomRequest) String() string            { return proto.CompactTextString(m) }
func (*UserOutOfRoomRequest) ProtoMessage()               {}
func (*UserOutOfRoomRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

// 103退出房间回复
type UserOutOfRoomResponse struct {
	Resultcode    int32  `protobuf:"varint,1,opt,name=Resultcode,json=resultcode" json:"Resultcode,omitempty"`
	NotifyMessage string `protobuf:"bytes,2,opt,name=NotifyMessage,json=notifyMessage" json:"NotifyMessage,omitempty"`
}

func (m *UserOutOfRoomResponse) Reset()                    { *m = UserOutOfRoomResponse{} }
func (m *UserOutOfRoomResponse) String() string            { return proto.CompactTextString(m) }
func (*UserOutOfRoomResponse) ProtoMessage()               {}
func (*UserOutOfRoomResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UserOutOfRoomResponse) GetResultcode() int32 {
	if m != nil {
		return m.Resultcode
	}
	return 0
}

func (m *UserOutOfRoomResponse) GetNotifyMessage() string {
	if m != nil {
		return m.NotifyMessage
	}
	return ""
}

// 104用户入座
type OthersEnterTable struct {
	ChairId  int32  `protobuf:"varint,1,opt,name=ChairId,json=chairId" json:"ChairId,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=NickName,json=nickName" json:"NickName,omitempty"`
}

func (m *OthersEnterTable) Reset()                    { *m = OthersEnterTable{} }
func (m *OthersEnterTable) String() string            { return proto.CompactTextString(m) }
func (*OthersEnterTable) ProtoMessage()               {}
func (*OthersEnterTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *OthersEnterTable) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *OthersEnterTable) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

// 105用户离座
type OthersLeaveTable struct {
	ChairId  int32  `protobuf:"varint,1,opt,name=ChairId,json=chairId" json:"ChairId,omitempty"`
	NickName string `protobuf:"bytes,2,opt,name=NickName,json=nickName" json:"NickName,omitempty"`
}

func (m *OthersLeaveTable) Reset()                    { *m = OthersLeaveTable{} }
func (m *OthersLeaveTable) String() string            { return proto.CompactTextString(m) }
func (*OthersLeaveTable) ProtoMessage()               {}
func (*OthersLeaveTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *OthersLeaveTable) GetChairId() int32 {
	if m != nil {
		return m.ChairId
	}
	return 0
}

func (m *OthersLeaveTable) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

// 201客户端加载成功
type UserFinishesLoadingRequest struct {
}

func (m *UserFinishesLoadingRequest) Reset()                    { *m = UserFinishesLoadingRequest{} }
func (m *UserFinishesLoadingRequest) String() string            { return proto.CompactTextString(m) }
func (*UserFinishesLoadingRequest) ProtoMessage()               {}
func (*UserFinishesLoadingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

// 202服务器反馈客户端捕鱼游戏操作错误
type UserMessageErrorResponse struct {
	Resultcode    int32  `protobuf:"varint,1,opt,name=Resultcode,json=resultcode" json:"Resultcode,omitempty"`
	NotifyMessage string `protobuf:"bytes,2,opt,name=NotifyMessage,json=notifyMessage" json:"NotifyMessage,omitempty"`
}

func (m *UserMessageErrorResponse) Reset()                    { *m = UserMessageErrorResponse{} }
func (m *UserMessageErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*UserMessageErrorResponse) ProtoMessage()               {}
func (*UserMessageErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UserMessageErrorResponse) GetResultcode() int32 {
	if m != nil {
		return m.Resultcode
	}
	return 0
}

func (m *UserMessageErrorResponse) GetNotifyMessage() string {
	if m != nil {
		return m.NotifyMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*GameUserData)(nil), "msg.GameUserData")
	proto.RegisterType((*Hello)(nil), "msg.Hello")
	proto.RegisterType((*UserLoginRequest)(nil), "msg.UserLoginRequest")
	proto.RegisterType((*UserLoginResponse)(nil), "msg.UserLoginResponse")
	proto.RegisterType((*UserLogoutRequest)(nil), "msg.UserLogoutRequest")
	proto.RegisterType((*UserLogoutResponse)(nil), "msg.UserLogoutResponse")
	proto.RegisterType((*UserRegisterRequest)(nil), "msg.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "msg.UserRegisterResponse")
	proto.RegisterType((*UserEnterRoomRequest)(nil), "msg.UserEnterRoomRequest")
	proto.RegisterType((*UserEnterRoomResponse)(nil), "msg.UserEnterRoomResponse")
	proto.RegisterType((*UserOutOfRoomRequest)(nil), "msg.UserOutOfRoomRequest")
	proto.RegisterType((*UserOutOfRoomResponse)(nil), "msg.UserOutOfRoomResponse")
	proto.RegisterType((*OthersEnterTable)(nil), "msg.OthersEnterTable")
	proto.RegisterType((*OthersLeaveTable)(nil), "msg.OthersLeaveTable")
	proto.RegisterType((*UserFinishesLoadingRequest)(nil), "msg.UserFinishesLoadingRequest")
	proto.RegisterType((*UserMessageErrorResponse)(nil), "msg.UserMessageErrorResponse")
	proto.RegisterEnum("msg.MessageId", MessageId_name, MessageId_value)
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x31, 0x6d, 0xdd, 0x66, 0x44, 0x91, 0xbb, 0xa5, 0x95, 0x55, 0x10, 0x42, 0x2b, 0x0e,
	0x88, 0x43, 0x2e, 0x3c, 0x02, 0x04, 0x62, 0x94, 0x0f, 0x64, 0xc1, 0x01, 0x04, 0x0a, 0x9b, 0x78,
	0xe2, 0xac, 0xb0, 0x77, 0xc3, 0xee, 0x1a, 0xc4, 0x63, 0xf0, 0xc6, 0xd5, 0x7e, 0x24, 0x71, 0x72,
	0x8d, 0x4f, 0xde, 0xff, 0xcc, 0xfa, 0xe7, 0xff, 0xcc, 0x58, 0x03, 0xbd, 0x5a, 0x97, 0xfd, 0xb5,
	0x92, 0x46, 0x92, 0x93, 0x5a, 0x97, 0xf4, 0x31, 0x3c, 0xfa, 0xc0, 0x6a, 0xfc, 0xa2, 0x51, 0xbd,
	0x63, 0x86, 0xd1, 0xa7, 0x70, 0x36, 0xc4, 0xaa, 0x92, 0x84, 0xc0, 0xa9, 0x60, 0x35, 0xa6, 0xd1,
	0x8b, 0xe8, 0x55, 0x2f, 0x77, 0x67, 0xfa, 0x11, 0x12, 0x7b, 0x71, 0x24, 0x4b, 0x2e, 0x72, 0xfc,
	0xdd, 0xa0, 0x36, 0xe4, 0x0e, 0x2e, 0x6c, 0x6c, 0xb2, 0xbb, 0x7b, 0xd1, 0x04, 0x6d, 0x73, 0x9f,
	0x98, 0xd6, 0x7f, 0xa5, 0x2a, 0xd2, 0x87, 0x3e, 0xb7, 0x0e, 0x9a, 0x7e, 0x85, 0xab, 0x16, 0x4b,
	0xaf, 0xa5, 0xd0, 0x48, 0x9e, 0x03, 0xe4, 0xa8, 0x9b, 0xca, 0x2c, 0x64, 0xe1, 0x71, 0x67, 0x39,
	0xa8, 0x6d, 0x84, 0xbc, 0x84, 0xcb, 0x89, 0x34, 0x7c, 0xf9, 0x6f, 0x8c, 0x5a, 0xb3, 0x12, 0x03,
	0xf5, 0x52, 0xb4, 0x83, 0xf4, 0x7a, 0x8b, 0x96, 0x8d, 0x09, 0x3e, 0xe9, 0x37, 0x20, 0xed, 0x60,
	0xa7, 0x1f, 0x1c, 0xc3, 0xb5, 0x65, 0xe7, 0x58, 0x72, 0x6d, 0xec, 0xf3, 0xb8, 0xd6, 0x7c, 0x87,
	0x27, 0xfb, 0xb8, 0x4e, 0xcd, 0xf6, 0x3d, 0x7d, 0x20, 0x2c, 0x5a, 0xca, 0x7a, 0xe3, 0xf6, 0x16,
	0x62, 0x2b, 0xb3, 0x22, 0x90, 0x63, 0xe5, 0x14, 0xfd, 0x1f, 0xc1, 0xcd, 0xc1, 0x0b, 0x5d, 0xfa,
	0x21, 0x29, 0x9c, 0x7f, 0x66, 0xf3, 0x0a, 0xb3, 0x22, 0x3d, 0x71, 0x88, 0x73, 0xe3, 0xa5, 0xcd,
	0xbc, 0x5d, 0x31, 0xae, 0xb2, 0x22, 0x3d, 0xf5, 0x99, 0x85, 0x97, 0xf4, 0xd6, 0xd7, 0x30, 0x6d,
	0xcc, 0x74, 0xd9, 0xaa, 0x81, 0xfe, 0xf0, 0x56, 0x5b, 0xf1, 0x4e, 0x5b, 0x37, 0x84, 0x64, 0x6a,
	0x56, 0xa8, 0xb4, 0xeb, 0x85, 0x73, 0xdd, 0x36, 0x19, 0xed, 0x99, 0xb4, 0x23, 0x9e, 0xf0, 0xc5,
	0x2f, 0x37, 0xfe, 0x30, 0x62, 0x11, 0xf4, 0x8e, 0x34, 0x42, 0xf6, 0x07, 0x8f, 0x21, 0x3d, 0x83,
	0x3b, 0x5b, 0xf2, 0x7b, 0x2e, 0xb8, 0x5e, 0xa1, 0x1e, 0x49, 0x56, 0x70, 0x51, 0x6e, 0x1a, 0xf2,
	0x13, 0x52, 0x9b, 0x0d, 0x05, 0x0c, 0x94, 0x92, 0x1d, 0xff, 0x4e, 0xaf, 0xfb, 0xd0, 0x0b, 0xc7,
	0xac, 0x20, 0x00, 0xf1, 0xcc, 0xad, 0x8f, 0xe4, 0x01, 0xb9, 0x81, 0xab, 0xd9, 0xe1, 0xb6, 0x48,
	0xa2, 0x79, 0xec, 0x96, 0xcf, 0x9b, 0xfb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x14, 0x97, 0x2f, 0x09,
	0x89, 0x04, 0x00, 0x00,
}
